version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: esii_db
    environment:
      POSTGRES_USER: esii
      POSTGRES_PASSWORD: esii
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: