-- Criar tabela event_manager
CREATE TABLE event_manager (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               is_email_verified BOOLEAN NOT NULL,
                               person_role SMALLINT NOT NULL CHECK (person_role BETWEEN 0 AND 2),
                               cpf_number VARCHAR(255) NOT NULL UNIQUE,
                               email VARCHAR(255) NOT NULL UNIQUE,
                               name VARCHAR(255) NOT NULL,
                               password VARCHAR(255) NOT NULL,
                               phone VARCHAR(255) NOT NULL
);

-- Criar tabela event_participant
CREATE TABLE event_participant (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   is_email_verified BOOLEAN NOT NULL,
                                   person_role SMALLINT NOT NULL CHECK (person_role BETWEEN 0 AND 2),
                                   cpf_number VARCHAR(255) NOT NULL UNIQUE,
                                   email VARCHAR(255) NOT NULL UNIQUE,
                                   name VARCHAR(255) NOT NULL,
                                   password VARCHAR(255) NOT NULL,
                                   phone VARCHAR(255) NOT NULL
);

-- Criar tabela main_event_type
CREATE TABLE main_event_type (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 name VARCHAR(255) NOT NULL
);

-- Criar tabela main_event
CREATE TABLE main_event (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            registration_price FLOAT(53) NOT NULL,
                            end_date_time TIMESTAMP(6) NOT NULL,
                            event_manager_id BIGINT NOT NULL,
                            main_event_type_id BIGINT NOT NULL,
                            start_date_time TIMESTAMP(6) NOT NULL,
                            address VARCHAR(255) NOT NULL,
                            title VARCHAR(255) NOT NULL,
                            CONSTRAINT FK_event_manager FOREIGN KEY (event_manager_id) REFERENCES event_manager,
                            CONSTRAINT FK_main_event_type FOREIGN KEY (main_event_type_id) REFERENCES main_event_type
);

-- Criar tabela main_event_action
CREATE TABLE main_event_action (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   quantity_vacancies INTEGER NOT NULL,
                                   registration_price FLOAT(53) NOT NULL,
                                   end_date_time TIMESTAMP(6) NOT NULL,
                                   event_manager_id BIGINT NOT NULL,
                                   main_event_id BIGINT NOT NULL,
                                   start_date_time TIMESTAMP(6) NOT NULL,
                                   address VARCHAR(255) NOT NULL,
                                   title VARCHAR(255) NOT NULL,
                                   CONSTRAINT FK_event_manager_action FOREIGN KEY (event_manager_id) REFERENCES event_manager,
                                   CONSTRAINT FK_main_event_action FOREIGN KEY (main_event_id) REFERENCES main_event
);
