-- Criando tabelas
CREATE TABLE event_subscription (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                    event_participant_id BIGINT NOT NULL,
                                    main_event_id BIGINT NOT NULL,
                                    PRIMARY KEY (id)
);

CREATE TABLE event_subscription_main_event_action_list (
                                                           event_subscription_id BIGINT NOT NULL,
                                                           main_event_action_list_id BIGINT NOT NULL UNIQUE
);

CREATE TABLE event_manager (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                               is_email_verified BOOLEAN NOT NULL,
                               person_role SMALLINT NOT NULL CHECK (person_role BETWEEN 0 AND 2),
                               cpf_number VARCHAR(255) NOT NULL UNIQUE,
                               email VARCHAR(255) NOT NULL UNIQUE,
                               name VARCHAR(255) NOT NULL,
                               password VARCHAR(255) NOT NULL,
                               phone VARCHAR(255) NOT NULL,
                               PRIMARY KEY (id)
);

CREATE TABLE event_participant (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                   is_email_verified BOOLEAN NOT NULL,
                                   person_role SMALLINT NOT NULL CHECK (person_role BETWEEN 0 AND 2),
                                   cpf_number VARCHAR(255) NOT NULL UNIQUE,
                                   email VARCHAR(255) NOT NULL UNIQUE,
                                   name VARCHAR(255) NOT NULL,
                                   password VARCHAR(255) NOT NULL,
                                   phone VARCHAR(255) NOT NULL,
                                   PRIMARY KEY (id)
);

CREATE TABLE main_event (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            registration_price FLOAT(53) NOT NULL,
                            start_date_time TIMESTAMP(6) NOT NULL,
                            end_date_time TIMESTAMP(6) NOT NULL,
                            address VARCHAR(255) NOT NULL,
                            title VARCHAR(255) NOT NULL,
                            event_manager_id BIGINT NOT NULL,
                            main_event_type_id BIGINT NOT NULL,
                            PRIMARY KEY (id)
);

CREATE TABLE main_event_action (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                   quantity_vacancies INTEGER NOT NULL,
                                   registration_price FLOAT(53) NOT NULL,
                                   start_date_time TIMESTAMP(6) NOT NULL,
                                   end_date_time TIMESTAMP(6) NOT NULL,
                                   address VARCHAR(255) NOT NULL,
                                   title VARCHAR(255) NOT NULL,
                                   event_manager_id BIGINT NOT NULL,
                                   main_event_id BIGINT NOT NULL,
                                   PRIMARY KEY (id)
);

CREATE TABLE main_event_type (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                 name VARCHAR(255) NOT NULL,
                                 PRIMARY KEY (id)
);

-- Adicionando constraints
ALTER TABLE event_subscription
    ADD CONSTRAINT FKppkqm9s6p3mug07ykc1bog7tg FOREIGN KEY (event_participant_id) REFERENCES event_participant;
ALTER TABLE event_subscription
    ADD CONSTRAINT FK3wa5o6pcaviktgnvodkikfe5i FOREIGN KEY (main_event_id) REFERENCES main_event;

ALTER TABLE event_subscription_main_event_action_list
    ADD CONSTRAINT FKlwdjjda08pg6r4qcgj1butube FOREIGN KEY (main_event_action_list_id) REFERENCES main_event_action;
ALTER TABLE event_subscription_main_event_action_list
    ADD CONSTRAINT FK5piwrrnnchq9p4u4ql197nwti FOREIGN KEY (event_subscription_id) REFERENCES event_subscription;

ALTER TABLE main_event
    ADD CONSTRAINT FK8djicqqdxq8plfx0yiwkpnsl0 FOREIGN KEY (event_manager_id) REFERENCES event_manager;
ALTER TABLE main_event
    ADD CONSTRAINT FK1mlk9ftib5m88bhgu1nj6yxgu FOREIGN KEY (main_event_type_id) REFERENCES main_event_type;

ALTER TABLE main_event_action
    ADD CONSTRAINT FKncxr96pmu3gbqjl4cj5opajgb FOREIGN KEY (event_manager_id) REFERENCES event_manager;
ALTER TABLE main_event_action
    ADD CONSTRAINT FKt19iwdbk24mw3nj98i9jkhevm FOREIGN KEY (main_event_id) REFERENCES main_event;
