-- Criação das tabelas principais

-- Tabela: event_participant
CREATE TABLE event_participant (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   is_email_verified BOOLEAN NOT NULL,
                                   person_role SMALLINT NOT NULL CHECK (person_role BETWEEN 0 AND 2),
                                   cpf_number VARCHAR(255) NOT NULL UNIQUE,
                                   email VARCHAR(255) NOT NULL UNIQUE,
                                   name VARCHAR(255) NOT NULL,
                                   password VARCHAR(255) NOT NULL,
                                   phone VARCHAR(255) NOT NULL
);

-- Tabela: event_manager
CREATE TABLE event_manager (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               is_email_verified BOOLEAN NOT NULL,
                               person_role SMALLINT NOT NULL CHECK (person_role BETWEEN 0 AND 2),
                               cpf_number VARCHAR(255) NOT NULL UNIQUE,
                               email VARCHAR(255) NOT NULL UNIQUE,
                               name VARCHAR(255) NOT NULL,
                               password VARCHAR(255) NOT NULL,
                               phone VARCHAR(255) NOT NULL
);

-- Tabela: main_event_type
CREATE TABLE main_event_type (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 name VARCHAR(255) NOT NULL
);

-- Tabela: main_event
CREATE TABLE main_event (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            title VARCHAR(255) NOT NULL,
                            address VARCHAR(255) NOT NULL,
                            registration_price FLOAT(53) NOT NULL,
                            start_date_time TIMESTAMP(6) NOT NULL,
                            end_date_time TIMESTAMP(6) NOT NULL,
                            event_manager_id BIGINT NOT NULL,
                            main_event_type_id BIGINT NOT NULL
);

-- Tabela: main_event_action
CREATE TABLE main_event_action (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   title VARCHAR(255) NOT NULL,
                                   address VARCHAR(255) NOT NULL,
                                   registration_price FLOAT(53) NOT NULL,
                                   quantity_vacancies INTEGER NOT NULL,
                                   start_date_time TIMESTAMP(6) NOT NULL,
                                   end_date_time TIMESTAMP(6) NOT NULL,
                                   event_manager_id BIGINT NOT NULL,
                                   main_event_id BIGINT NOT NULL
);

-- Tabela: event_subscription
CREATE TABLE event_subscription (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    event_participant_id BIGINT NOT NULL,
                                    main_event_id BIGINT NOT NULL
);

-- Tabela de junção: event_subscription_main_event_action_list
CREATE TABLE event_subscription_main_event_action_list (
                                                           event_subscription_id BIGINT NOT NULL,
                                                           main_event_action_list_id BIGINT NOT NULL UNIQUE
);

-- Tabela de junção: main_event_action_event_participant
CREATE TABLE main_event_action_event_participant (
                                                     main_event_action_id BIGINT NOT NULL,
                                                     event_participant_id BIGINT NOT NULL,
                                                     PRIMARY KEY (main_event_action_id, event_participant_id)
);

-- Adição de chaves estrangeiras

-- Relacionamento entre event_subscription e event_participant
ALTER TABLE event_subscription
    ADD CONSTRAINT FK_event_subscription_participant
        FOREIGN KEY (event_participant_id)
            REFERENCES event_participant;

-- Relacionamento entre event_subscription e main_event
ALTER TABLE event_subscription
    ADD CONSTRAINT FK_event_subscription_event
        FOREIGN KEY (main_event_id)
            REFERENCES main_event;

-- Relacionamento entre event_subscription_main_event_action_list e main_event_action
ALTER TABLE event_subscription_main_event_action_list
    ADD CONSTRAINT FK_event_action
        FOREIGN KEY (main_event_action_list_id)
            REFERENCES main_event_action;

-- Relacionamento entre event_subscription_main_event_action_list e event_subscription
ALTER TABLE event_subscription_main_event_action_list
    ADD CONSTRAINT FK_event_subscription
        FOREIGN KEY (event_subscription_id)
            REFERENCES event_subscription;

-- Relacionamento entre main_event e event_manager
ALTER TABLE main_event
    ADD CONSTRAINT FK_main_event_manager
        FOREIGN KEY (event_manager_id)
            REFERENCES event_manager;

-- Relacionamento entre main_event e main_event_type
ALTER TABLE main_event
    ADD CONSTRAINT FK_main_event_type
        FOREIGN KEY (main_event_type_id)
            REFERENCES main_event_type;

-- Relacionamento entre main_event_action e event_manager
ALTER TABLE main_event_action
    ADD CONSTRAINT FK_main_event_action_manager
        FOREIGN KEY (event_manager_id)
            REFERENCES event_manager;

-- Relacionamento entre main_event_action e main_event
ALTER TABLE main_event_action
    ADD CONSTRAINT FK_main_event_action_event
        FOREIGN KEY (main_event_id)
            REFERENCES main_event;

-- Relacionamento entre main_event_action_event_participant e main_event_action
ALTER TABLE main_event_action_event_participant
    ADD CONSTRAINT FK_main_event_action_event_participant_action
        FOREIGN KEY (main_event_action_id)
            REFERENCES main_event_action (id);

-- Relacionamento entre main_event_action_event_participant e event_participant
ALTER TABLE main_event_action_event_participant
    ADD CONSTRAINT FK_main_event_action_event_participant_participant
        FOREIGN KEY (event_participant_id)
            REFERENCES event_participant (id);

-- Tabela de junção: main_event_event_participant
CREATE TABLE main_event_event_participant (
                                              main_event_id BIGINT NOT NULL,
                                              event_participant_id BIGINT NOT NULL,
                                              PRIMARY KEY (main_event_id, event_participant_id),
                                              CONSTRAINT FK_main_event FOREIGN KEY (main_event_id) REFERENCES main_event (id),
                                              CONSTRAINT FK_event_participant FOREIGN KEY (event_participant_id) REFERENCES event_participant (id)
);
